/**
 * Supported icon names for the AppIcon component.
 *
 * Icons are Lucide-style stroke SVGs (MIT licensed). All path data is
 * hardcoded in icon.component.ts so the bundle only ships what is used.
 */
export type AppIconName =
  | 'activity'
  | 'arrow-left'
  | 'bell'
  | 'bell-ring'
  | 'briefcase'
  | 'calendar'
  | 'check'
  | 'chevron-left'
  | 'chevron-right'
  | 'circle-alert'
  | 'circle-check'
  | 'clock'
  | 'copy'
  | 'download'
  | 'external-link'
  | 'eye'
  | 'eye-off'
  | 'file-plus'
  | 'file-text'
  | 'globe'
  | 'home'
  | 'history'
  | 'inbox'
  | 'info'
  | 'layers'
  | 'layout-dashboard'
  | 'list-filter'
  | 'loader'
  | 'log-out'
  | 'mail'
  | 'map-pin'
  | 'menu'
  | 'pencil'
  | 'plus'
  | 'refresh'
  | 'search'
  | 'send'
  | 'settings'
  | 'shield-check'
  | 'sparkle'
  | 'kanban'
  | 'star'
  | 'sun'
  | 'moon'
  | 'trash'
  | 'triangle-alert'
  | 'user'
  | 'wand'
  | 'x'
  | 'chart';
